version: "3"

services:
  email-sender:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - EMAIL_ADDRESS=${EMAIL_ADDRESS:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
    restart: unless-stopped
