services:
  - type: web
    name: email-generator
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /_stcore/health
    envVars:
      - key: PORT
        value: 10000
