services:
  - type: web
    name: email-ai-assistant
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8501
      - key: G4F_API_HOST
        value: localhost
      - key: G4F_API_PORT
        value: 1337
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
