services:
  - type: web
    name: email-generator
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /_stcore/health
    envVars:
      - key: PORT
        value: 10000
      - key: G4F_API_HOST
        value: 127.0.0.1
      - key: G4F_API_PORT
        value: 8080
